# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a212285af230cdebe8c78cf61377591bf0d96159645acb336dbc4b5b2c68013030d497b4b3f9aee4f9c3b12d6b1528c6fb794d8522e8cd88235346d214e9ad4c

test:
  secret_key_base: 4d67a608914e443d5601116d42c4ec9358e64465e7bf83ae690596a0943fa4e6da81b298b6a5834435b51b79e33c274646196e64431e25ec106701ac3593dd33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
